name: Emacs lib publisher

on:
  push:
    paths-ignore:
      - '*.org'
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      #     cache: 'npm'
      #     persist-credentials: false
      # - run: npm ci
      # - run: npm test

      - name: Install dependency
        run: |
          mkdir -p "/tmp/tmp"
          mkdir -p "/tmp/mylib/plantuml"          
          # mkdir -p "/tmp/mylib/lsp/npm"
          # mkdir -p "/tmp/mylib/lsp/lua"
          mkdir -p "/tmp/mylib/tree-sitter"          

      - name: Install plantuml
        run: |
          sudo wget https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O /tmp/mylib/plantuml/plantuml.jar

      # - name: Cd tmp directory
      #   run: |
      #     cd /tmp/tmp

      # - name: Clone repository lua-language-server
      #   uses: GuillaumeFalourd/clone-github-repo-action@v2
      #   with:
      #     owner: 'sumneko'
      #     repository: 'lua-language-server'
          
      # - name: Install lua lsp
      #   run: |          
      #     cd lua-language-server
      #     TAGNUM=$(git describe --tags `git rev-list --tags --max-count=1`)
      #     sudo wget https://github.com/sumneko/lua-language-server/releases/download/$TAGNUM/lua-language-server-$TAGNUM-darwin-x64.tar.gz
      #     tar xzf lua-language-server-$TAGNUM-darwin-x64.tar.gz -C /tmp/mylib/lsp/lua

      # - name: Install npm for lsp
      #   run: |
      #     cd /tmp/mylib/lsp/npm
      #     npm install bash-language-server pyright typescript-language-server @volar/vue-language-server vscode-langservers-extracted yaml-language-server

      - name: Cd tmp directory
        run: |
          cd /tmp/tmp

      - name: Clone repository tree-sitter
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'casouri'
          repository: 'tree-sitter-module'

      - name: Build tree-sitter
        run: |
          cd tree-sitter-module
          ./batch.sh
          cp -r dist/* /tmp/mylib/tree-sitter/

      - name: Commit files for lib
        run: |
          cd /tmp/mylib
          ls -al
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "$(date '+%y/%m/%d %H:%M:%S')"

      - name: Push for lib
        uses: ad-m/github-push-action@master
        with:
          directory: /tmp/mylib
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: lib
          force: true
